steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
      - '-f'
      - 'Rejection-Mapper 2.0folder-name/Dockerfile'
      - 'Rejection-Mapper 2.0folder-name'

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'

options:
  logging: CLOUD_LOGGING_ONLY
