services:
  - type: web
    name: rejection-mapper
    runtime: node
    rootDir: Rejection-Mapper
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
